### ISSUE TITLE
Login - Front End

### ISSUE THREAD

**Issue by abdulrauf623** [bruno-boys/ftl-capstone#10]
# Story
As a user, i want to log back into my account to view my previously saved data.

# Description:
I am creating a login page to allow the user to log back into the account every time they want to.

## Acceptance Criteria
- [ ] Create a login form that takes in the following parameters:
         - username and password
 - [ ] Create an on submit function that makes a post request to the auth/login route. Use the results from the post request to log the user into the account
 - [ ] If the user is authenticated, grant them access to the activity page that is specific to the username and password combination
 - [ ] Pass the on submit function to a submit button or log in button on the log in form.

### DoD
- [ ] Acceptance Criteria Satisfied
- [ ] Merge Request
- [ ] Ticket connected to merge request
- [ ] Tests pass

**Comment by aloyeoshotse** [comment]
The submit function should have a corresponding submit button that sends the post request.
Could also talk about what happens after the user logs in (what page it goes to for example)
